# Generated by Django 2.2.3 on 2019-11-11 19:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Duration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_of_duration', models.CharField(max_length=64)),
                ('Limite inferior', models.IntegerField()),
                ('limite superior', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ProductType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='VariableEconomic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameVariable', models.CharField(max_length=64)),
                ('value', models.FloatField()),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='banco', to='pointofequilibrium.Bank')),
                ('duration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='duracion', to='pointofequilibrium.Duration')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_joined', models.DateTimeField(verbose_name='date joined')),
                ('auth_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectionType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('productType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productTypeOnProjections', to='pointofequilibrium.ProductType')),
            ],
        ),
        migrations.CreateModel(
            name='Projection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('type_of_projection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projectionType', to='pointofequilibrium.ProjectionType')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
                ('variableEconomic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variableEconomic', to='pointofequilibrium.VariableEconomic')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('productType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productType', to='pointofequilibrium.ProductType')),
            ],
        ),
    ]
