# Generated by Django 2.2.3 on 2019-11-14 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pointofequilibrium', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DurationMonths',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Tiempo en meses', models.IntegerField()),
            ],
        ),
    ]
