# Generated by Django 2.2.3 on 2019-11-15 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pointofequilibrium', '0002_durationmonths'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DurationMonths',
        ),
        migrations.RenameField(
            model_name='duration',
            old_name='Limite inferior',
            new_name='Limite_inferior',
        ),
        migrations.RenameField(
            model_name='duration',
            old_name='limite superior',
            new_name='limite_superior',
        ),
    ]
